export default {
    dialogVisible: false,
    dialogName: '',
    upconfig: true,
    getdatabasenames: {},
    getsqlcategory: {},
    operatefun: '',
    copefun: '',
    secretkeyfun: '',
    taskfun: '',
    configipfun: '',
    abnormalsdata: [],
    copedetailsdata: [],
    userdata: [],
    version: '',
    buildPC: false,
    secretkey: false,
    activeName: 'task',
    routepath: ''
}